### ISSUE TITLE
Python 2 , python 3 and javascript frontend failure 

### ISSUE THREAD

**Issue by akashcas** [auvsi-suas/interop#109]
I again tried to setup test server in the new dedicated system and i am unable to pass the test after git pull  i am getting following failure . 

```
asnmims@Akash:~$ bash setup.sh
bash: setup.sh: No such file or directory
uasnmims@Akash:~$ bash /interop/test.sh
Testing server...
Creating test database for alias 'default'...
........................................................................................................................................Obstacle Info Rate (148.819147)
..........................UAS Post Rate (248.806797)
....................................................................Server Info Rate (205.849299)
.....................
----------------------------------------------------------------------
Ran 251 tests in 81.608s

OK
Destroying test database for alias 'default'...

=====================================================================

Testing Python 2 client...
EEEEE.E.................
======================================================================
ERROR: Test getting obstacles.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/uasnmims/interop/client/interop/client_test.py", line 54, in setUp
    self.client = Client(server, username, password)
  File "/home/uasnmims/interop/client/interop/client.py", line 49, in __init__
    'password': password})
  File "/home/uasnmims/interop/client/interop/client.py", line 78, in post
    raise InteropError(r)
InteropError: POST http://localhost/api/login -> 400 Error (BAD REQUEST): Invalid Credentials.
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /api/login HTTP/1.1" 400 None
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Test getting server info.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/uasnmims/interop/client/interop/client_test.py", line 54, in setUp
    self.client = Client(server, username, password)
  File "/home/uasnmims/interop/client/interop/client.py", line 49, in __init__
    'password': password})
  File "/home/uasnmims/interop/client/interop/client.py", line 78, in post
    raise InteropError(r)
InteropError: POST http://localhost/api/login -> 400 Error (BAD REQUEST): Invalid Credentials.
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /api/login HTTP/1.1" 400 None
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Test sending some (incorrect) telemetry.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/uasnmims/interop/client/interop/client_test.py", line 54, in setUp
    self.client = Client(server, username, password)
  File "/home/uasnmims/interop/client/interop/client.py", line 49, in __init__
    'password': password})
  File "/home/uasnmims/interop/client/interop/client.py", line 78, in post
    raise InteropError(r)
InteropError: POST http://localhost/api/login -> 400 Error (BAD REQUEST): Invalid Credentials.
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /api/login HTTP/1.1" 400 None
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Test sending some telemetry.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/uasnmims/interop/client/interop/client_test.py", line 54, in setUp
    self.client = Client(server, username, password)
  File "/home/uasnmims/interop/client/interop/client.py", line 49, in __init__
    'password': password})
  File "/home/uasnmims/interop/client/interop/client.py", line 78, in post
    raise InteropError(r)
InteropError: POST http://localhost/api/login -> 400 Error (BAD REQUEST): Invalid Credentials.
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /api/login HTTP/1.1" 400 None
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Test target workflow.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/uasnmims/interop/client/interop/client_test.py", line 54, in setUp
    self.client = Client(server, username, password)
  File "/home/uasnmims/interop/client/interop/client.py", line 49, in __init__
    'password': password})
  File "/home/uasnmims/interop/client/interop/client.py", line 78, in post
    raise InteropError(r)
InteropError: POST http://localhost/api/login -> 400 Error (BAD REQUEST): Invalid Credentials.
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /api/login HTTP/1.1" 400 None
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Simple login test.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/uasnmims/interop/client/interop/client_test.py", line 26, in test_login
    Client(server, username, password)
  File "/home/uasnmims/interop/client/interop/client.py", line 49, in __init__
    'password': password})
  File "/home/uasnmims/interop/client/interop/client.py", line 78, in post
    raise InteropError(r)
InteropError: POST http://localhost/api/login -> 400 Error (BAD REQUEST): Invalid Credentials.
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /api/login HTTP/1.1" 400 None
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 24 tests in 0.691s

FAILED (errors=6)

=====================================================================

Testing Python 3 client...
EEEEE.E.................
======================================================================
ERROR: Test getting obstacles.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/uasnmims/interop/client/interop/client_test.py", line 54, in setUp
    self.client = Client(server, username, password)
  File "/home/uasnmims/interop/client/interop/client.py", line 49, in __init__
    'password': password})
  File "/home/uasnmims/interop/client/interop/client.py", line 78, in post
    raise InteropError(r)
nose.proxy.InteropError: POST http://localhost/api/login -> 400 Error (BAD REQUEST): Invalid Credentials.
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /api/login HTTP/1.1" 400 None
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Test getting server info.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/uasnmims/interop/client/interop/client_test.py", line 54, in setUp
    self.client = Client(server, username, password)
  File "/home/uasnmims/interop/client/interop/client.py", line 49, in __init__
    'password': password})
  File "/home/uasnmims/interop/client/interop/client.py", line 78, in post
    raise InteropError(r)
nose.proxy.InteropError: POST http://localhost/api/login -> 400 Error (BAD REQUEST): Invalid Credentials.
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /api/login HTTP/1.1" 400 None
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Test sending some (incorrect) telemetry.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/uasnmims/interop/client/interop/client_test.py", line 54, in setUp
    self.client = Client(server, username, password)
  File "/home/uasnmims/interop/client/interop/client.py", line 49, in __init__
    'password': password})
  File "/home/uasnmims/interop/client/interop/client.py", line 78, in post
    raise InteropError(r)
nose.proxy.InteropError: POST http://localhost/api/login -> 400 Error (BAD REQUEST): Invalid Credentials.
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /api/login HTTP/1.1" 400 None
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Test sending some telemetry.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/uasnmims/interop/client/interop/client_test.py", line 54, in setUp
    self.client = Client(server, username, password)
  File "/home/uasnmims/interop/client/interop/client.py", line 49, in __init__
    'password': password})
  File "/home/uasnmims/interop/client/interop/client.py", line 78, in post
    raise InteropError(r)
nose.proxy.InteropError: POST http://localhost/api/login -> 400 Error (BAD REQUEST): Invalid Credentials.
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /api/login HTTP/1.1" 400 None
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Test target workflow.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/uasnmims/interop/client/interop/client_test.py", line 54, in setUp
    self.client = Client(server, username, password)
  File "/home/uasnmims/interop/client/interop/client.py", line 49, in __init__
    'password': password})
  File "/home/uasnmims/interop/client/interop/client.py", line 78, in post
    raise InteropError(r)
nose.proxy.InteropError: POST http://localhost/api/login -> 400 Error (BAD REQUEST): Invalid Credentials.
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /api/login HTTP/1.1" 400 None
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Simple login test.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/uasnmims/interop/client/interop/client_test.py", line 26, in test_login
    Client(server, username, password)
  File "/home/uasnmims/interop/client/interop/client.py", line 49, in __init__
    'password': password})
  File "/home/uasnmims/interop/client/interop/client.py", line 78, in post
    raise InteropError(r)
nose.proxy.InteropError: POST http://localhost/api/login -> 400 Error (BAD REQUEST): Invalid Credentials.
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /api/login HTTP/1.1" 400 None
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 24 tests in 0.617s

FAILED (errors=6)

=====================================================================

Testing JavaScript Frontend...
21 04 2016 14:00:26.096:INFO [karma]: Karma v0.13.21 server started at http://localhost:9876/
21 04 2016 14:00:26.101:INFO [launcher]: Starting browser PhantomJS
21 04 2016 14:00:26.109:ERROR [phantomjs.launcher]: execvp(): No such file or directory

21 04 2016 14:01:26.135:WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
21 04 2016 14:01:28.136:WARN [launcher]: PhantomJS was not killed in 2000 ms, sending SIGKILL.
21 04 2016 14:01:30.140:WARN [launcher]: PhantomJS was not killed by SIGKILL in 2000 ms, continuing.

=====================================================================

Server PASSED
Python 2 client FAILED
Python 3 client FAILED
JavaScript Frontend FAILED
uasnmims@Akash:~$ 
```

**Comment by pmtischler** [comment]
Please read the log you posted. It has the reason it didn't work in it.
