### ISSUE TITLE
interop client library issue

### ISSUE THREAD

**Issue by parvu** [auvsi-suas/interop#229]
When I try to use interop client library to obtain missions information I get the following error: 

 python command:  
         client.get_missions()
result:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/interop/client.py", line 124, in get_missions
    return [Mission.deserialize(m) for m in r.json()]
  File "/usr/local/lib/python2.7/dist-packages/interop/types.py", line 58, in deserialize
    return cls(**d)
TypeError: __init__() got an unexpected keyword argument 'stationary_obstacles'

seems mission class in types is not correct.

Workaround:
client.get('/api/missions')

**Comment by pmtischler** [comment]
You're executing the test as an admin- so it returns additional fields that the client library doesn't accept. If you test as a non-admin (what a team would be at competition), this works fine.
