### ISSUE TITLE
Interop 400 Error (Bad Request)

### ISSUE THREAD

**Issue by dhost88** [auvsi-suas/interop#369]
Hello,
This is Devin from Flinthill School's Animus Ferus. We recently installed the newest version of Interop and to test connectivity, we used the client side docker image. We followed the set up of the host computer and the client side docker image step by step on the getting started wiki. We ran this command: 

./tools/interop_cli.py --url http://10.10.130.2:8000 --username testuser missions

On the client side computer and then we used the password 'testpass'. However we consistantly receieved this error message:

Traceback (most recent call last):
 File "./tools/interop_cli.py", line 144, in <module>
   main()
 File "./tools/interop_cli.py", line 139, in main
   client = Client(args.url, args.username, password)
 File "/interop/client/interop/client.py", line 55, in __init__
   'password': password})
 File "/interop/client/interop/client.py", line 84, in post
   raise InteropError(r)
interop.exceptions.InteropError: POST http://10.10.130.2:8000/api/login -> 400 Error (Bad Request): Failed to parse request.

We were able to ping the server from the client computer, leading us to believe that there may be an other underlying issue.

**Comment by pmtischler** [comment]
Did you upgrade both the client image and the server image? The APIs have changed.

**Comment by dhost88** [comment]
We are using the most recent images from Docker Hub

**Comment by pmtischler** [comment]
As part of the continuous integration test we execute your failing request. So it's unlikely to be a code issue and more likely to be an issue with your deployment.

The error indicates it's an invalid request (400) and that it couldn't parse it. That sounds like one is using the new API (proto based) and one is using the old API (post param based). I'd bet you updated one of the containers but not both.

**Comment by dhost88** [comment]
We had to completely wipe all of the docker images on both the client and server, we then reinstalled them both. This resoved the issue

Thanks for your help

**Comment by pmtischler** [comment]
For future reference, you likely had to stop and restart the container in order to pick up the updated image. Either that or you weren't updating the image correctly so by clearing it the system downloaded it fresh.
