### ISSUE TITLE
interop installation issue 

### ISSUE THREAD

**Issue by Akumaar** [auvsi-suas/interop#380]
I'm running the following commands to install interop and i'm using python2.7:

git clone https://github.com/auvsi-suas/interop
cd interop/client
pip install -r requirements.txt
pip install . -U

Errors im receiving:

============== Errors========================

Error checking for conflicts.

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 503, in _warn_about_conflicts

    package_set, _dep_info = check_install_conflicts(to_install)

  File "/usr/local/lib/python2.7/site-packages/pip/_internal/operations/check.py", line 108, in check_install_conflicts

    package_set, _ = create_package_set_from_installed()

  File "/usr/local/lib/python2.7/site-packages/pip/_internal/operations/check.py", line 47, in create_package_set_from_installed

    package_set[name] = PackageDetails(dist.version, dist.requires())

  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2589, in version

    raise ValueError(tmpl % self.PKG_INFO, self)

ValueError: ("Missing 'Version:' header and/or METADATA file", Unknown [unknown version] (/usr/local/lib/python2.7/site-packages))

==========================================================

Please let me know if you know of a solution to the above issue.

**Comment by pmtischler** [comment]
Please read the Wiki's Getting Started guide which describes how to properly install the library. The commands you executed are not the ones we recommend, so we won't debug it for you.
