### ISSUE TITLE
interop_cli.py: error: invalid choice: 'teams'

### ISSUE THREAD

**Issue by cannonj17** [auvsi-suas/interop#462]
receiving the error ```interop_cli.py: error: invalid choice: 'teams'``` upon execution of 
``` ./tools/interop_cli.py --url http://localhost:8000 --username testuser teams```

Sorry if this is my mistake, but in any case, the usage message has not been updated to reflect the new teams api

**Comment by pmtischler** [comment]
Have you updated your Docker image?

**Comment by pmtischler** [comment]
The `teams` is added to the parser here:
https://github.com/auvsi-suas/interop/blob/master/client/tools/interop_cli.py#L86

And smoke tested here:
https://github.com/auvsi-suas/interop/blob/master/client/tools/interop_cli_test.py#L30

**Comment by cannonj17** [comment]
I forgot to update the image. I have now done that, but I am having more issues with it. I only receive the 403 error when requesting teams (missions works fine), and I am assuming the port error is the result of using the same port to host and request. What might I be doing wrong?
```
loyuav@UAV-Loyola-Ubuntu16:~/interop/server$ sudo ./interop-server.sh up
server_interop-db_1 is up-to-date
Creating server_interop-server_1 ... error

ERROR: for server_interop-server_1  Cannot start service interop-server: driver failed programming external connectivity on endpoint server_interop-server_1 (75ff826a207f22564d2cf63d3a44b1190c0ae125041ef8b6ecd64c3a80a128ba): Bind for 0.0.0.0:8000 failed: port is already allocated

ERROR: for interop-server  Cannot start service interop-server: driver failed programming external connectivity on endpoint server_interop-server_1 (75ff826a207f22564d2cf63d3a44b1190c0ae125041ef8b6ecd64c3a80a128ba): Bind for 0.0.0.0:8000 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
loyuav@UAV-Loyola-Ubuntu16:~/interop/server$ cd ../client
loyuav@UAV-Loyola-Ubuntu16:~/interop/client$ sudo ./interop-client.sh run
(venv2) root@UAV-Loyola-Ubuntu16:/interop/client# ./tools/interop_cli.py --url http://localhost:8000 --username testuser teams
Interoperability Password: 
Traceback (most recent call last):
  File "./tools/interop_cli.py", line 156, in <module>
    main()
  File "./tools/interop_cli.py", line 152, in main
    args.func(args, client)
  File "./tools/interop_cli.py", line 22, in teams
    teams = client.get_teams().result()
  File "/interop/client/venv2/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()
  File "/interop/client/venv2/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/interop/client/auvsi_suas/client/client.py", line 131, in get_teams
    r = self.get('/api/teams')
  File "/interop/client/auvsi_suas/client/client.py", line 74, in get
    raise InteropError(r)
auvsi_suas.client.exceptions.InteropError: GET http://localhost:8000/api/teams -> 403 Error (Forbidden): <h1>403 Forbidden</h1>
```

**Comment by pmtischler** [comment]
If you read the error message, you're already hosting a web server at port `8000`.

```
Bind for 0.0.0.0:8000 failed: port is already allocated
```

The error `403` is a permissions error. You're logged in but accessing an administrator API. The `/api/teams` was an admin API, and new in SUAS 2020 it's now accessible by teams. Did you remember to update the server image as well?
