### ISSUE TITLE
issue with db_create

### ISSUE THREAD

**Issue by coolpig123** [auvsi-suas/interop#538]
hello my name is yoav and i am from the Haifa Reali robotics team. 
i tried to download the interop server on another computer and i have encountered an issue. when running the command : 
``` sudo ./interop-server.sh create_db```
i get an error :
```Starting server_interop-db_1 ... done
Creating server_interop-server_run ... done
2022-06-13 10:52:11,330: __main__: INFO: Health Check
2022-06-13 10:52:11,331: __main__: INFO: Checking postgres...
2022-06-13 10:52:26,382: __main__: INFO: Checking postgres...
2022-06-13 10:52:41,469: __main__: INFO: Checking postgres...
2022-06-13 10:52:56,542: __main__: INFO: Checking postgres...
2022-06-13 10:53:11,622: __main__: INFO: Checking postgres...
Traceback (most recent call last):
  File "./healthcheck.py", line 63, in <module>
    main()
  File "./healthcheck.py", line 57, in main
    check_postgres(args.postgres_host, args.postgres_user)
  File "/usr/local/lib/python3.8/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.8/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "./healthcheck.py", line 21, in check_postgres
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pg_isready', '-q', '-h', 'interop-db', '-U', 'postgres']' returned non-zero exit status 2.
ERROR: 1

what should i do?

**Comment by coolpig123** [comment]
i fixed the issue
