### ISSUE TITLE
python2 fails on first run of test.sh

### ISSUE THREAD

**Issue by justineaster** [auvsi-suas/interop#8]
I git pulled the most recent changes. I then created a new vagrant machine, ran setup.sh, then ran test.sh. The Python2 test failed. I ran test.sh a second time and all tests passed. Below is the output.

```
vagrant@vagrant-ubuntu-trusty-64:~/interop$ ./test.sh 
Testing server...
Creating test database for alias 'default'...
................................................................................................................................................................................................................UAS Post Rate (174.986346)
......Server Info Rate (125.038069)
...........Obstacle Info Rate (100.393715)
.........
----------------------------------------------------------------------
Ran 234 tests in 105.419s

OK
Destroying test database for alias 'default'...

=====================================================================

Testing Python 2 client...
EE..............
======================================================================
ERROR: Test getting obstacles.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/interop/client/interop/client_test.py", line 54, in setUp
    self.client = Client(server, username, password)
  File "/home/vagrant/interop/client/interop/client.py", line 46, in __init__
    'password': password})
  File "/home/vagrant/interop/client/interop/client.py", line 75, in post
    r = self.session.post(self.url + uri, timeout=self.timeout, **kwargs)
  File "/interop/client/venv2/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/interop/client/venv2/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/interop/client/venv2/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/interop/client/venv2/local/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='localhost', port=80): Read timed out. (read timeout=1)
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Test getting server info.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/interop/client/interop/client_test.py", line 54, in setUp
    self.client = Client(server, username, password)
  File "/home/vagrant/interop/client/interop/client.py", line 46, in __init__
    'password': password})
  File "/home/vagrant/interop/client/interop/client.py", line 75, in post
    r = self.session.post(self.url + uri, timeout=self.timeout, **kwargs)
  File "/interop/client/venv2/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/interop/client/venv2/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/interop/client/venv2/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/interop/client/venv2/local/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='localhost', port=80): Read timed out. (read timeout=1)
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 16 tests in 5.360s

FAILED (errors=2)

=====================================================================

Testing Python 3 client...
................
----------------------------------------------------------------------
Ran 16 tests in 2.021s

OK

=====================================================================

Testing JavaScript Frontend...
02 11 2015 22:07:37.365:INFO [karma]: Karma v0.13.14 server started at http://localhost:9876/
02 11 2015 22:07:37.372:INFO [launcher]: Starting browser PhantomJS
02 11 2015 22:07:38.120:INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket f8nRvHZczZKPyqeXAAAA with id 9324519
PhantomJS 1.9.8 (Linux 0.0.0): Executed 15 of 15 SUCCESS (0.052 secs / 0.052 secs)

=====================================================================

Server PASSED
Python 2 client FAILED
Python 3 client PASSED
JavaScript Frontend PASSED
vagrant@vagrant-ubuntu-trusty-64:~/interop$ ./test.sh 
Testing server...
Creating test database for alias 'default'...
................................................................................................................................................................................................................UAS Post Rate (176.993734)
......Server Info Rate (124.911775)
...........Obstacle Info Rate (100.971334)
.........
----------------------------------------------------------------------
Ran 234 tests in 106.336s

OK
Destroying test database for alias 'default'...

=====================================================================

Testing Python 2 client...
................
----------------------------------------------------------------------
Ran 16 tests in 2.246s

OK

=====================================================================

Testing Python 3 client...
................
----------------------------------------------------------------------
Ran 16 tests in 1.942s

OK

=====================================================================

Testing JavaScript Frontend...
02 11 2015 22:11:12.276:INFO [karma]: Karma v0.13.14 server started at http://localhost:9876/
02 11 2015 22:11:12.283:INFO [launcher]: Starting browser PhantomJS
02 11 2015 22:11:12.622:INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket RQDxMrm31E8oXO8jAAAA with id 35986502
PhantomJS 1.9.8 (Linux 0.0.0): Executed 15 of 15 SUCCESS (0.088 secs / 0.052 secs)

=====================================================================

Server PASSED
Python 2 client PASSED
Python 3 client PASSED
JavaScript Frontend PASSED
```

**Comment by prattmic** [comment]
Ah, yes. This is a known issue.  The problem is that the shared filesystem that Vagrant is using is really slow. When the tests make the first request, Apache loads the Python server from disk. The Vagrant shared filesystem is so slow that the test request times out before the server is ready to handle it. Once loaded, the server remains in memory and this problem goes away.

I'll work on fixing this.
