### ISSUE TITLE
Exporting database to JSON

### ISSUE THREAD

**Issue by DarkmatterVale** [auvsi-suas/interop#89]
Hi,

How can I export the database to a JSON file?

Thanks!

**Comment by pmtischler** [comment]
https://docs.djangoproject.com/en/1.8/ref/django-admin/#dumpdata-app-label-app-label-app-label-model

**Comment by DarkmatterVale** [comment]
This is the error that I get when I run ```python manage.py dumpdata auvsi_suas```:

```
robotics@robotics:~/interop/server$ python manage.py dumpdata auvsi_suas
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robotics/interop/server/auvsi_suas/models/__init__.py", line 12, in <module>
    from target import Target, TargetType, Color, Shape, Orientation
  File "/home/robotics/interop/server/auvsi_suas/models/target.py", line 9, in <module>
    class Choices(enum.IntEnum):
AttributeError: 'module' object has no attribute 'IntEnum'
```

Any ideas why?

**Comment by pmtischler** [comment]
First, you don't need to specify `auvsi_suas`.

Second, you need to source the virtual environment.

**Comment by DarkmatterVale** [comment]
Thank you that worked!

**Comment by pmtischler** [comment]
Np
