### ISSUE TITLE
Travis NPM fetch errors

### ISSUE THREAD

**Issue by prattmic** [auvsi-suas/interop#94]
I think this may be the issue: https://github.com/npm/npm/issues/12196

Builds are failing like:

```
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token 
npm ERR! ï¿½ï¿½Sï¿½nï¿½0ï¿½ï¿½caSï¿½ï¿½Ä¶ï¿½ï¿½ï¿½Iï¿½ï¿½(ï¿½$ï¿½#ï¿½Iï¿½U
ï¿½{ï¿½ï¿½ï¿½ï¿½]ï¿½tD<ß½ï¿½ï¿½taZ(`ï¿½ï¿½ï¿½d'ï¿½ï¿½&dï¿½wï¿½ï¿½ï¿½qï¿½ï¿½Yqa~ï¿½Cyï¿½ï¿½>
ï¿½Kï¿½"ï¿½iï¿½ï¿½Kï¿½ï¿½
npm ERR! ï¿½,ï¿½ï¿½P~]R'-ï¿½>5pJtï¿½"4ï¿½ï¿½ï¿½ï¿½ï¿½C?ï¿½ï¿½gc+ÇŠï¿½YXgï¿½ï¿½T
ï¿½}_21ï¿½ï¿½ï¿½ jï¿½ï¿½ï¿½uï¿½ï¿½tï¿½,Fï¿½/T
J`Pï¿½ï¿½ï¿½Iï¿½*ï¿½ï¿½R$5=ï¿½
npm ERR! ï¿½Dï¿½Nï¿½ï¿½ï¿½ï¿½~ï¿½2ï¿½Dï¿½)ï¿½ ï¿½ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Kiï¿½Ù‘ï¿½ï¿½ï¿½ï¿½0hrï¿½ï¿½6U-rï¿½ï¿½ï¿½ï¿½Oï¿½T$DRï¿½ï¿½Ó‘LRï¿½ï¿½Ñ }ï¿½ï¿½ï¿½bSï¿½\Yï¿½ï¿½8ï¿½ï¿½&en ï¿½ï¿½	ï¿½sdHï¿½kï¿½ï¿½ï¿½_Æ—ï¿½sï¿½ï¿½Ë­QÐ‹&ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½3VTï¿½ï¿½ï¿½Zï¿½
npm ERR! ]ï¿½ï¿½
npm ERR! 7(ï¿½ï¿½ï¿½ï¿½
ï¿½ï¿½zï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½9ï¿½ï¿½]ï¿½ï¿½ï¿½Õ‡\ï¿½ï¿½ï¿½yaKÚ›I)ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½qcï¿½d=[ï¿½ï¿½*vï¿½ï¿½ï¿½<ï¿½Ö„ï¿½<Hï¿½ï¿½ï¿½}ï¿½ï¿½-ï¿½l'ï¿½1tï¿½,l?ï¿½XaM<=DMï¿½ï¿½/ï¿½|ï¿½$ï¿½vï¿½v^_xeSï¿½
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-33-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--global" "karma-phantomjs-launcher"
npm ERR! cwd /home/travis/build/auvsi-suas/interop
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_token
```

**Comment by pmtischler** [comment]
That documentation says it's fixed in later versions of `npm`, and that the Ubuntu 14.04 default `npm` is super old / insecure / unable to upgrade.

**Comment by prattmic** [comment]
After much "fixed"/"reopened"/"fixed", etc on the linked bug, they seem to have finally fixed it server side.
